services:
  weechat:
    image: ghcr.io/ksurl/weechat
    container_name: weechat
    network_mode: bridge
    stdin_open: true
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    restart: unless-stopped
