version: "3"
services:
  flexget:
    image: ghcr.io/ksurl/weechat
    container_name: weechat
    network_mode: bridge
    stdin_open: true
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - <HOST>/config:/config
      - <HOST>/downloads:/downloads
    restart: unless-stopped
